name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Hugo
    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.142.0' # Specify the Hugo version

    # Step 3: Build the site using Hugo
    - name: Build the Hugo site
      run: hugo --minify 

    # Step 4: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./public # This is the folder Hugo generates the site
        github_token: ${{ secrets.GITHUB_TOKEN }} # Token to authenticate with GitHub
